.PHONY: up down demo-up demo-down demo-check slug

up:
	./bin/dev-up

down:
	./bin/dev-down

demo-up:
	./bin/dev-demo-parallel up

demo-down:
	./bin/dev-demo-parallel down

demo-check:
	./bin/dev-demo-parallel check

slug:
	./bin/slug.sh
