.PHONY: ingress-up ingress-down up down slug demo-up demo-down demo-check

ingress-up:
	./bin/ingress-up

ingress-down:
	./bin/ingress-down

up:
	./bin/dev-up

down:
	./bin/dev-down

slug:
	./bin/slug.sh

demo-up:
	./bin/dev-demo-parallel up

demo-down:
	./bin/dev-demo-parallel down

demo-check:
	./bin/dev-demo-parallel check
